/*
 * Code generated by goctl-android. DO NOT EDIT.
 *
 * Copyright [2020] [ClientCall]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.tal.service;

import com.tal.bean.*;
import okhttp3.RequestBody;
import retrofit2.Call;
import retrofit2.http.*;

public interface IService {
    // 登录
	@POST("/api/user/login")
	Call<Void> login(@Body RequestBody req);
	// 注册
	@POST("/api/user/register")
	Call<Void> register(@Body RequestBody req);
	// 用户搜索
	@GET("/api/user/search")
	Call<UserInfoReply> searchUser(@Query("keyWord") String keyWord);
	// 获取用户信息
	@GET("/api/user/{id}")
	Call<UserInfoReply> getUserInfo(@Path("id") String id);
	
}